services:
  app:
    build:
      context: ./tests/docker/
      dockerfile: unoserver.Dockerfile
    container_name: unoserver-tests
    volumes:
      - ./tests/docker/data:/data
    ports:
      - "2003:2003"