name: UnoserverClient
on: [push, pull_request]
jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: curl, xmlrpc
      - uses: actions/checkout@v2

      -   name: Validate composer config
          run: composer validate --strict

      -   name: Composer Install
          run: composer install --ansi --prefer-dist --no-interaction --no-progress

      -   name: Run PHPCSFixer
          run: composer style:check
  phpunit:
    name: PHPUnit ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
    steps:
      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ matrix.php }}
              extensions: curl, xmlrpc

      -   uses: actions/checkout@v2

      -   name: Composer Install
          run: composer install --ansi --prefer-dist --no-interaction --no-progress

      -   name: Run phpunit
          run: composer test